FROM python:slim

WORKDIR /root/test_dima_tech

COPY ${REPO_DIR} /root/test_dima_tech/

RUN apt-get update && \
    apt-get -y install git build-essential libssl-dev libffi-dev libpq-dev && \
    pip3 install -r requirements.txt
