# Generated by Django 4.1.2 on 2022-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_bill_billmodel_rename_product_productmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'products'},
        ),
    ]
