# Generated by Django 4.1.2 on 2022-10-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billmodel',
            options={'verbose_name_plural': 'bills'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'verbose_name_plural': 'transactions'},
        ),
    ]
